### ISSUE TITLE
Add .env module

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-rem-server#1]
Simplify configuration to use environment variables for local dev as well as server

**Comment by talltom** [comment]
Hi @mgvarley looks great!

**Comment by mgvarley** [comment]
Plan is to use the dotenv library to complement existing config https://www.npmjs.com/package/dotenv.  This is a very lightweight library that allows defining a file (.env) which if present will be read at startup and any variables contained will be made environment variables accessible as process.env.DB_PASSWORD for example, actual environment variables will always take precedent over .env.  This allows the developer to use a .env file to run the application in dev without having to manually edit the config.js and the same application to then port to staging / prod without modification and without the risk of sensitive information passing into the code repo (.env file is in .gitignore).  It also will help new developers get up and running quickly.

**Comment by mgvarley** [comment]
I have noticed that environment variables are named: RDS_USERNAME, RDS_HOSTNAME, RDS_PORT - these are not necessarily RDS specific and a developer running locally might be running a local Postgres instance.  Also you may want to move away from RDS in the future.  Would there be any issue with renaming these DB_USERNAME, DB_HOSTNAME and DB_PORT?  They would need to be updated in Beanstalk and any CD/CI before the next deployment.  @talltom @matthewberryman what do you think?

**Comment by matthewberryman** [comment]
Yes agree on names (these were put in with EB/RDS in mind but are non-specific) and have changed in d24ce65.

**Comment by mgvarley** [comment]
OK great, thanks Matthew.  This issue is now closed then as fixed in latest development branch
