### ISSUE TITLE
Evaluate MassiveJS to support Postgres interactions

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-rem-server#5]
Considerations:
- How to catch disconnect errors?
- Reports module
- Server module
- REM Server module

**Comment by matthewberryman** [comment]
PostGIS is another consideration. See https://github.com/robconery/massive-js/issues?utf8=%E2%9C%93&q=postgis (although the issues are closed, it seems that's as a result of people developing workarounds from the quick glance I've seen)

**Comment by mgvarley** [comment]
@talltom @matthewberryman I am planning to use this https://github.com/vitaly-t/pg-promise rather than plain pg - it handles promises natively and is very active (330k downloads in the last month).  I will be splitting out the sql into separate files for ease of maintenance and readability, don't think we need massiveJs however I will keep an eye on this.  Let me know if you have any concerns.

**Comment by talltom** [comment]
Hi Mark, does it use node pg under the hood? Definitely want to checkout
our error handling for database disconnects, this code works and we don't
want to change it. Other frameworks (e.g. Massive don't support event
driven stuff as well as this). Second, we'll need to know if it uses pure
js or pg C bindings as this has tripped us in the past. Lastly, I would
also flag that this will mean we're using different db modules for reports
and server module which isn't ideal.

Given that db connectivity is core do we think we can do enough testing
before launch to introduce new module at this stage?

Welcome both your input/discussion on this.

--
@talltom

**Comment by mgvarley** [comment]
Hi Tom - yes it uses pg under the hood, it just wraps this with promises (promise library configurable, uses vanilla ES6 Promises by default) and adds some extra conveniences:


Built on top of node-postgres and its connection pool, this library translates their callback interface into one based on Promises/A+, while extending the protocol to a higher level, with automated connections and transactions management.


In addition, the library provides:


its own, more flexible query formatting;
event reporting for connectivity, errors, queries and transactions;
support for all popular promise libraries + ES6 generators;
declarative approach to controlling query results.



Given that we have said that we plan to use ES6 on both the client and server side now it would be good to be able to take advantage of some of these features and also further extend the use of Promises as opposed to callbacks which I know you are already doing.  If in the future you chose to route all DB calls via the API then the difference between this and reporting is probably not too big a deal.  If you did want to move reports to be in line with server and use promises for pg that should be fairly straightforward too.


What do you think?


Mark




  





Mark Varley

Envision

mark@envision-it.co.uk


+44 7545 697159

+44 118 3240442

1 Beacontree Plaza, Gillette Way, Reading, Berks RG2 0BS

**Comment by talltom** [comment]
Hi Mark,

Based on your comments above then this sounds like the way to go. One last
step would be to get @matthewberryman <https://github.com/matthewberryman>'s
agreement on this?

But if using PG under the hood should be OK.

Also note that regarding this issue specifically, I've evaluated MassiveJS
and confident that it's not the right framework for us at the moment, so
this looks like a good alternative.

--
@talltom

**Comment by matthewberryman** [comment]
Yes this seems find, and splitting out the SQL is definitely a good idea for the reasons @mgvarley mentioned

**Comment by talltom** [comment]
Great. As we're now going for pg-promise and @mgvarley talked me through it I'm happy to close this.
