### ISSUE TITLE
DIMS calls are breaking rem server

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-rem-server#8]
When trying to launch a fresh install of the rem-server the application fails to load correctly as it cannot find DB table "dims_reports".  This is due to DIMS functionality being removed from the DB schema however still present in the server code.

**Comment by mgvarley** [comment]
Awaiting confirmation from team as to whether we should remove DIMS completely.  For time being commenting out all DIMS references from the code

**Comment by fadmastuti** [comment]
@mgvarley thanks.
@talltom , we have discussed with BPBD Jakarta here about DIMS update. They agree to remove DIMS from REM this year as the API didn't work well when we tried to integrate.

p.s BPBD is in the process of replacing those library system (DIMS) with another one.

cc @anexact

**Comment by mgvarley** [comment]
All DIMS references removed, closing issue
