### ISSUE TITLE
Log files growing out of control

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-rem-server#9]
Just headed off for lunch and came back to a 100mb+ log file!  Log entries were predominantly:

2016-10-25T11:46:26.298Z - error: Postgres reconnection failed, queuing next attempt for 180000ms
2016-10-25T11:46:26.298Z - error: Postgres connection error: Error: connect ECONNREFUSED 127.0.0.1:54322
2016-10-25T11:46:26.298Z - info: Attempting to reconnect at intervals

My SSH tunnel had timed out and I has lost my connection to the DB.  This could cause issues in the future so should be resolved.

**Comment by matthewberryman** [comment]
We already have log rotation set up and working as per https://github.com/urbanriskmap/cognicity-rem-server/blob/master/server.js#L88 and we could revise down the max file size although I think 100MB is fine (?)

**Comment by mgvarley** [comment]
Agree log rotation is setup well and no changes needed there, I think the issue is that the DB retries are very chatty and if the DB is unavailable for, say 20 minutes, due to network issues the log files will fill up very quickly and when rotated could push out genuine issues and/or make it harder to debug.  Will take a look at the DB error logging when I start looking at MassiveJS

**Comment by matthewberryman** [comment]
Yeah, some things to review are the number of log messages from database issues, and the log level they're at—not just for database but also more generally. An outage of 20 minutes would be a massive outage in terms of our dev environment and especially in prod, however (where we use a multi-az RDS instance).
